use_frameworks!

platform :ios, '10.0'

target 'SDKLibraryNetwork_Example' do
  pod 'SDKLibraryNetwork', :path => '../'

  target 'SDKLibraryNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
